---
services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    networks:
      pact-broker:
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  pact-broker:
    image: "pactfoundation/pact-broker:2.130.0-pactbroker2.115.0"
    ports:
      - "9292:9292"
    networks:
      pact-broker:
    depends_on:
      - postgres
    environment:
      PACT_BROKER_PORT: '9292'
      PACT_BROKER_DATABASE_URL: "postgres://postgres:password@postgres/postgres"
      PACT_BROKER_LOG_LEVEL: INFO
      PACT_BROKER_SQL_LOG_LEVEL: DEBUG
      # PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES is only needed for docker-compose
      # because the database takes longer to start up than the puma process
      # Should not be needed in production.
      PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: "5"
      # The list of allowed base URLs (not setting this makes the app vulnerable to cache poisoning)
      # This list allows the app to be addressed from the host and from within another docker container correctly
      # Ngnix config below makes the app accessible on ports 443 and 80, while the Ruby application itself runs on port 9292
      PACT_BROKER_BASE_URL: 'https://localhost http://localhost http://localhost:9292 http://pact-broker:9292 https://host.docker.internal http://host.docker.internal http://host.docker.internal:9292'
      # https://docs.pact.io/pact_broker/configuration/settings#authentication-and-authorization
      PACT_BROKER_BASIC_AUTH_ENABLED: true
      PACT_BROKER_BASIC_AUTH_USERNAME: agile-glue-rw
      PACT_BROKER_BASIC_AUTH_PASSWORD: agile-glue-rw-pass
      PACT_BROKER_BASIC_AUTH_READ_ONLY_USERNAME: agile-glue-ro
      PACT_BROKER_BASIC_AUTH_READ_ONLY_PASSWORD: agile-glue-ro-pass

  pact-client:
    profiles:
      - cli
    image: "pactfoundation/pact-cli:1.4.0.6"
    networks:
      pact-broker:
    depends_on:
      - pact-broker
    environment:
      PACT_BROKER_BASE_URL: "http://pact-broker:9292"
      PACT_BROKER_USERNAME: agile-glue-rw
      PACT_BROKER_PASSWORD: agile-glue-rw-pass
      PACT_BROKER_BASIC_AUTH_READ_ONLY_USERNAME: agile-glue-ro
      PACT_BROKER_BASIC_AUTH_READ_ONLY_PASSWORD: agile-glue-ro-pass

  pact-client-remote:
    profiles:
      - cli
    image: "pactfoundation/pact-cli:1.4.0.6"
    environment:
      PACT_BROKER_BASE_URL: ${PACT_BROKER_BASE_URL}
      PACT_BROKER_USERNAME: ${PACT_BROKER_USERNAME}
      PACT_BROKER_PASSWORD: ${PACT_BROKER_PASSWORD}

volumes:
  postgres-volume:

networks:
  pact-broker:
    external: true
...
